# Generated by Django 4.1.7 on 2023-04-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("U", "User"), ("SU", "Superuser"), ("AD", "Admin")],
                default="U",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a name for the team", max_length=50
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter Pokemon species name", max_length=20
                    ),
                ),
                (
                    "nickname",
                    models.CharField(help_text="Enter Pokemon nickname", max_length=20),
                ),
                (
                    "type1",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("FIRE", "Fire"),
                            ("WATER", "Water"),
                            ("ELECTRIC", "Electric"),
                            ("GRASS", "Grass"),
                            ("ICE", "Ice"),
                            ("FIGHTING", "Fighting"),
                            ("POISON", "Poison"),
                            ("GROUND", "Ground"),
                            ("FLYING", "Flying"),
                            ("PSYCHIC", "Psychic"),
                            ("BUG", "Bug"),
                            ("ROCK", "Rock"),
                            ("GHOST", "Ghost"),
                            ("DRAGON", "Dragon"),
                            ("DARK", "Dark"),
                            ("STEEL", "Steel"),
                            ("FAIRY", "Fairy"),
                        ],
                        default="NORMAL",
                        help_text="Enter first type of the Pokemon",
                        max_length=8,
                        verbose_name="First type",
                    ),
                ),
                (
                    "type2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORMAL", "Normal"),
                            ("FIRE", "Fire"),
                            ("WATER", "Water"),
                            ("ELECTRIC", "Electric"),
                            ("GRASS", "Grass"),
                            ("ICE", "Ice"),
                            ("FIGHTING", "Fighting"),
                            ("POISON", "Poison"),
                            ("GROUND", "Ground"),
                            ("FLYING", "Flying"),
                            ("PSYCHIC", "Psychic"),
                            ("BUG", "Bug"),
                            ("ROCK", "Rock"),
                            ("GHOST", "Ghost"),
                            ("DRAGON", "Dragon"),
                            ("DARK", "Dark"),
                            ("STEEL", "Steel"),
                            ("FAIRY", "Fairy"),
                        ],
                        default="",
                        help_text="Enter second type of the Pokemon",
                        max_length=8,
                        verbose_name="Second type",
                    ),
                ),
                ("hp", models.IntegerField(verbose_name="Health points")),
                ("atk", models.IntegerField(verbose_name="Attack")),
                ("spatk", models.IntegerField(verbose_name="Special attack")),
                ("defense", models.IntegerField(verbose_name="Defense")),
                ("spdef", models.IntegerField(verbose_name="Special defense")),
                ("spd", models.IntegerField(verbose_name="Speed")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.team"
                    ),
                ),
            ],
        ),
    ]
