# Generated by Django 4.1.7 on 2023-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0004_alter_customuser_user_type_team_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="nickname",
            field=models.CharField(
                blank=True, help_text="Enter Pokemon nickname", max_length=20
            ),
        ),
    ]
