# Generated by Django 4.1.7 on 2023-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0005_alter_pokemon_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter name of the move", max_length=20),
                ),
                ("description", models.TextField(help_text="Enter move description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHYS", "Physical"),
                            ("SPEC", "Special"),
                            ("STAT", "Status"),
                        ],
                        help_text="Enter move category",
                        max_length=4,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("FIRE", "Fire"),
                            ("WATER", "Water"),
                            ("ELECTRIC", "Electric"),
                            ("GRASS", "Grass"),
                            ("ICE", "Ice"),
                            ("FIGHTING", "Fighting"),
                            ("POISON", "Poison"),
                            ("GROUND", "Ground"),
                            ("FLYING", "Flying"),
                            ("PSYCHIC", "Psychic"),
                            ("BUG", "Bug"),
                            ("ROCK", "Rock"),
                            ("GHOST", "Ghost"),
                            ("DRAGON", "Dragon"),
                            ("DARK", "Dark"),
                            ("STEEL", "Steel"),
                            ("FAIRY", "Fairy"),
                        ],
                        help_text="Enter move type",
                        max_length=8,
                    ),
                ),
                (
                    "power",
                    models.IntegerField(
                        blank=True, help_text="Enter move power if applicable"
                    ),
                ),
                (
                    "accuracy",
                    models.IntegerField(
                        blank=True, help_text="Enter move accuracy if applicable"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="move1",
            field=models.ManyToManyField(
                related_name="move1manager", to="mainApp.move"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="move2",
            field=models.ManyToManyField(
                related_name="move2manager", to="mainApp.move"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="move3",
            field=models.ManyToManyField(
                related_name="move3manager", to="mainApp.move"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="move4",
            field=models.ManyToManyField(
                related_name="move4manager", to="mainApp.move"
            ),
        ),
    ]
