# Generated by Django 4.1.7 on 2023-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0009_alter_team_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="accuracy",
            field=models.IntegerField(
                blank=True, help_text="Enter move accuracy if applicable", null=True
            ),
        ),
        migrations.AlterField(
            model_name="move",
            name="power",
            field=models.IntegerField(
                blank=True, help_text="Enter move power if applicable", null=True
            ),
        ),
    ]
