# Generated by Django 4.1.7 on 2023-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0010_alter_move_accuracy_alter_move_power"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="owner",
        ),
        migrations.AddField(
            model_name="team",
            name="owner_id",
            field=models.IntegerField(default=1, verbose_name="Owner ID"),
        ),
    ]
