# Generated by Django 4.1.7 on 2023-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0011_remove_team_owner_team_owner_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="ability",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="moves",
            field=models.ManyToManyField(blank=True, null=True, to="mainApp.move"),
        ),
    ]
