# Generated by Django 4.1.7 on 2023-04-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0012_pokemon_ability_alter_pokemon_moves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.team",
            ),
        ),
    ]
